name: NodeJS with Webpack

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm run build

    - name: Call function with checked-out branch name
      run: npm run upload-cloudinary -- pms
      env:
        CL_NAME: ${{ secrets.CL_NAME }}
        CL_APIKEY: ${{ secrets.CL_APIKEY }}
        CL_APISECRET: ${{ secrets.CL_APISECRET }}


